spring:
  application:
    name: backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

cloudinary:
  folder:
    cover: music-workspace/projects/%s/cover
    audio: music-workspace/projects/%s/tracks/%s/versions
