spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:music_workspace}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug
