spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_test
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false
